export const games = `CREATE TABLE IF NOT EXISTS games (
  id VARCHAR(50) PRIMARY KEY,
  stage VARCHAR(50) NOT NULL,
  turn int(1),
  winner VARCHAR(226),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8`;

export const players = `CREATE TABLE IF NOT EXISTS players (
    id int AUTO_INCREMENT PRIMARY KEY,
    gameId VARCHAR(50),
    isHost BOOLEAN,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(gameId) REFERENCES games(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8`;

export const gridCells = `CREATE TABLE IF NOT EXISTS gridCells (
  id VARCHAR(2),
  gameId VARCHAR(50),
  value VARCHAR(1),
  PRIMARY KEY(id, gameId),  
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(gameId) REFERENCES games(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8`;
